# DocFxMarkdownGen config file
# Requires running `docfx docfx/docfx.json` first

outputPath: ../../../api/Meadow.Foundation.FeatherWings
yamlPath: ../../api/Meadow.Foundation.FeatherWings
indexSlug: /api/Meadow.Foundation.FeatherWings
