# DocFxMarkdownGen config file
# Requires running `docfx docfx/docfx.json` first

outputPath: ../../../docs/api/Meadow.Foundation.mikroBUS
yamlPath: ../../api/Meadow.Foundation.mikroBUS
indexSlug: /api/Meadow.Foundation.mikroBUS
