# DocFxMarkdownGen config file
# Requires running `docfx docfx/docfx.json` first

outputPath: ../../../docs/api/Meadow.Foundation
yamlPath: ../../api/Meadow.Foundation
indexSlug: /api/Meadow.Foundation