# DocFxMarkdownGen config file
# Requires running `docfx docfx/docfx.json` first

outputPath: ../../../docs/api/Meadow.Foundation.Grove
yamlPath: ../../api/Meadow.Foundation.Grove
indexSlug: /api/Meadow.Foundation.Grove
