name: "[prod] Publish static site"

on:
  workflow_dispatch:
  push:
    branches: [ "docusaurus", "develop" ]
  pull_request:
    branches: [ "docusaurus", "develop" ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: beta
    steps:
      # Clone current repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src
          # ref: develop # <-- required to deploy beta docs
          
      - name: Run common build steps
        uses: ./.github/workflows/common-publish-steps.yml
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: './src/build'
          container_name: '$web'
          connection_string: ${{ secrets.DEVELOPER_DOCUSAURUS_BLOB_CONNECTIONSTRING }}
          overwrite: 'true'
          #sync: 'true'

      # Purge Azure Front Door Cache
      - name: Log into Azure        
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Purge Cache
        run: |
              az afd endpoint purge -g ${{ vars.RESOURCE_GROUP }} --profile-name ${{ vars.AFD_PROFILE_NAME }} --domains ${{ vars.AFD_DOMAINS }} --content-paths '/*' --endpoint-name ${{ vars.AFD_ENDPOINT_NAME }}
